apiVersion: v1
kind: Service
metadata:
  name: datomic-transactor
  labels:
    app: datomic-transactor
spec:
  ports:
    - name: datomic-transactor
      protocol: TCP
      port: 4334
      targetPort: 4334
  selector:
    app: datomic-transactor